<sws:dynamic-wsdl id="personne"                                                           (1)
    portTypeName="Inscription"                                                         (3)
    locationUri="/FakeOSM/"                                                       (4)                             (5)
  <sws:xsd location="/WEB-INF/xsd/Personne.xsd"/>                                                  (2)
</sws:dynamic-wsdl>